package com.coleccion.videojuegos.entity.Enums;

public enum Plataforma {
    NES,
    Sega_Master_System,
    Game_Boy,
	Game_Boy_Color,
    Sega_Genesis,
    Super_Nintendo,
    Sega_CD,
    Sega_32X,
    Atari_Jaguar,
    Panasonic_3DO,
    Virtual_Boy,
    PSX,
    Sega_Saturn,
    Nintendo_64,
    Sega_Dreamcast,
    PS2,
    Xbox,
    GameCube,
    Game_Boy_Advance,
    Nintendo_DS,
    PSP,
    Xbox_360,
    PS3,
    Wii,
    PSVita,
    Nintendo_3DS,
    Wii_U,
    PS4,
    Xbox_One,
    Nintendo_Switch,
    PS5,
    Xbox_Series_X,
    Xbox_Series_S
}